Status =
    OMOTE: 0
    URA: 1
    MOTIGOMA: 2

FIRST = -1
SECOND = 1
COLS = 7
ROWS = 7
MAX_VALUE = 50000
MIN_VALUE = -50000
UTIFUDUME = 30000
CHECKMATE = -30000
# 7 x 3
KIFU_ROW_LENGTH = 21
# 7 x 3 行末スペースが削られてるケース
KIFU_ROW_LENGTH_SUB = 20
KIFU_KOMA_LENGTH = 3
TEMP_HISTORY = 'history_file'
TEMP_DUPLICATION = 'duplication_file'

module.exports =
    Status: Status
    FIRST: FIRST
    SECOND: SECOND
    COLS: COLS
    ROWS: ROWS
    MAX_VALUE: MAX_VALUE
    MIN_VALUE: MIN_VALUE
    UTIFUDUME: UTIFUDUME
    CHECKMATE: CHECKMATE
    KIFU_ROW_LENGTH: KIFU_ROW_LENGTH
    KIFU_ROW_LENGTH_SUB: KIFU_ROW_LENGTH_SUB
    KIFU_KOMA_LENGTH: KIFU_KOMA_LENGTH
    TEMP_HISTORY: TEMP_HISTORY
    TEMP_DUPLICATION: TEMP_DUPLICATION
